name: "Build"

on:
  push:
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: "Setup PHP 8.0"
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "8.2"
          extensions: "yaml"

      - name: "Get version"
        id: metadata
        run: |
          echo "VERSION=$(php -r 'echo explode("+", explode("-", yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["version"])[0])[0];')" >> $GITHUB_OUTPUT
          echo "FULL_VERSION=$(php -r 'echo yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["version"];')" >> $GITHUB_OUTPUT
          echo "NAME=$(php -r 'echo yaml_parse_file(getcwd() . "/src/main/resources/plugin.yml")["name"];')" >> $GITHUB_OUTPUT

      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: "maven"

      - name: "Build with Maven"
        run: mvn -B package --file pom.xml

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "build-${{ steps.metadata.outputs.VERSION }}"
          path: target/CloudBridge.jar